### ISSUE TITLE
ValueError: Unknown layer: InstanceNormalization.

### ISSUE THREAD

**Issue by liamquin** [fengwang/super_resolution#2]
Installed wit h pip and resources folder copied, and cusa installed even though i have the nouveau driver in use...  so using the sample Python with the three  lines uncommented...

```super_resolution ./liam-discord-128x128.png foo.png
WARNING:tensorflow:From /home/lee/.local/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/lee/.local/lib/python3.9/site-packages/tensorflow/python/ops/init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/lee/.local/lib/python3.9/site-packages/tensorflow/python/ops/init_ops.py:97: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
  File "/home/lee/.local/bin/super_resolution", line 8, in <module>
    sys.exit(main())
  File "/home/lee/.local/lib/python3.9/site-packages/super_resolution/entry_points.py", line 24, in main
    cartoon_upsampling_4x( input_image_path, output_image_path )
  File "/home/lee/.local/lib/python3.9/site-packages/super_resolution/super_resolution.py", line 204, in cartoon_upsampling_4x
    cartoon_model = read_model( model_path )
  File "/home/lee/.local/lib/python3.9/site-packages/super_resolution/super_resolution.py", line 39, in read_model
    model = model_from_json( model_json )
  File "/home/lee/.local/lib/python3.9/site-packages/keras/saving/model_config.py", line 104, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/home/lee/.local/lib/python3.9/site-packages/keras/layers/serialization.py", line 208, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/lee/.local/lib/python3.9/site-packages/keras/utils/generic_utils.py", line 674, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/home/lee/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 662, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "/home/lee/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 1273, in reconstruct_from_config
    process_layer(layer_data)
  File "/home/lee/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 1255, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/lee/.local/lib/python3.9/site-packages/keras/layers/serialization.py", line 208, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/lee/.local/lib/python3.9/site-packages/keras/utils/generic_utils.py", line 659, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "/home/lee/.local/lib/python3.9/site-packages/keras/utils/generic_utils.py", line 556, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown layer: InstanceNormalization. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
```

**Comment by ANANYANAYAN** [comment]
I am also facing the same issue. Please help.

**Comment by fengwang** [comment]
@liamquin @ANANYANAYAN  Sorry for my late reply. I have updated the code base. Can you please try again?
